name: Continuous Integration

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Linting and Style Check
        uses: psf/black@stable

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
 
      - name: Run Python Unit Tests
        uses: python3 -m unittest